### ISSUE TITLE
Default style for introductions should be different than Bible text

### ISSUE THREAD

**Issue by alerque** [crosswire/xiphos#845] opened 2017-11-13 08:29 UTC
As noted in [this issue](https://github.com/adyeths/u2o/issues/17) for an OSIS conversion tool, most properly generated OSIS files have chapter introductions tagged in a way that delimits them from the following Bible content. These div tags should be rendered with a different style in the user interface by default.

What that style is could be debated. Many print Bibles use italic, some use a different (often lighter weight) font or use a sans font where the Bible is rendered in a serif font. Whatever the typography ends up being, the default presentation should be visually distinguishable.

**Comment by domcorbex** [comment] 2017-11-14 17:01
Maybe it is not a well-documented feature, but Xiphos has already built-in support for custom CSS styles.

1. Add the configuration directive `PreferredCSSXHTML=style.css` to your module.conf file.
style.css is the name of the CSS file in the module's DataPath directory. 

2. Create the CSS file.
Example:
```/* Header */
.moduleHeader, .testamentHeader, .bookHeader, .chapterHeader{
    font-weight: bold ;
    text-align: center ;
}

/* Chapter description */
.x-ChapterDescription {
    font-weight: normal ;
    font-style: italic ;
    font-size: 90% ;
    text-align: center ;
}```

**Comment by karlkleinpaste** [comment] 2018-04-08 04:24
though i would prefer to use CSS for this, i am not aware that libsword offers any distinguishing class for pre-chapter and -book introductory material. therefore, at least for the time being, i have implemented a simple italic boundary around it. this distinguishes it pretty obviously from the chapter text proper.

**Comment by greg-hellings** [comment] 2018-04-08 07:00
Can you not just wrap it with a span or div and set an appropriate class? That's all the engine would do.

**Comment by karlkleinpaste** [comment] 2018-04-08 12:31
here's my dilemma.
i could change to wrap with <span class="introductory-material">...</span> or somesuch. that would let someone use CSS on that name. but it would have no good way to be documented (as dom mentioned, there's already precious little clue for the user about PreferredCSSXHTML) and it would be peculiar and unrelated to any other front end.
or i could leave it as it now is, using <i>...</i>, so that it provides a distinguishing visual characteristic for all users as soon as the next release comes out, not just those with CSS understanding, with a future plan to encourage a sword release that provides this The Right Way i.e. by having intro material wrapped in such a span class as well as providing a default CSS control the way the engine already does for divineName, transChange, wordsOfJesus, etc.
i did it the latter way because the former seems doomed to be really useless, while providing the desired visual effect starting a week from now when i put out 4.0.8.
i'm not being a pig about this, but i'd like to hear, shall we say, a robust defense of the really really general version for only the extremely informed few over the yeah-it's-way-too-specific version that takes care of everybody almost immediately though not being tunable by the illuminati.
(fyi, ESV2011 provides good examples of per-book intro in every 1:1.)

**Comment by karlkleinpaste** [comment] 2018-04-08 12:34
I HATE GITHUB'S SUCKTASTIC EDITOR.

please interpolate with me:
...i could change to wrap with [span class="introductory-material"]...[/span] or somesuch...
...using [i]...[/i], so that it provides...

I REALLY REALLY REALLY WANT TO BE ABLE TO TYPE ANGLE BRACKETS. HONEST, I DO.

**Comment by karlkleinpaste** [comment] 2018-04-08 21:52
i figured i'd go ahead and do the CSS thing anyhow. what the heck...no matter what i do here, if the engine gets around to providing it some day, i'd have to change xiphos then anyhow, so why not do as much as i can for the time being.

problem is, i've inserted a handler element in HTML_START (at the top of display.cc), and then replaced [i]...[/i] wrapping of the intro text with [div class="introMaterial"]...[/div] (interpolate angle brackets with me here). this has the unintended result that the entire chapter is italicized. _sigh_ why does the bounding of [div]...[/div] not constrain the application of the .introMaterial spec?

i've experimented with personalization of this in ~/.xiphos/default_style.css, to add "color: yellow" for .introMaterial, and yes indeed it turns the whole chapter yellow, not just the intro.

example: at ESV2011 1Th.1.1, the block resulting from this change is:

[div class="introMaterial"] [div sID="gen34165" type="introduction"/][br /] Paul wrote this letter to encourage new believers in their faith, to exhort them to godly living, to give them assurance about the eternal state of believers who had died, and to defend the integrity of his ministry as an apostle. Thessalonica (present-day Thessaloniki, Greece) was the capital of Roman Macedonia. It was on important trade routes. Paul, twice identified as the author (1:1; 2:18), visited Thessalonica on his second missionary journey but was forced to flee because of Jewish opposition. He sent Timothy to work with the largely Gentile church there, and Timothy brought him good news of their faith (3:6). This is one of Paul’s first letters, probably written about a.d. 50–51. [br /][div eID="gen34165" type="introduction"/][br /][br /] [/div]

simple diff that generates this from today's source:
[display.cc.txt](https://github.com/crosswire/xiphos/files/1887959/display.cc.txt)

is webkit misinterpreting the bounds of the standalone [div ... /] elements? i can hardly believe that would be the cause.

**Comment by greg-hellings** [comment] 2018-04-09 02:08
On Sun, Apr 8, 2018 at 4:52 PM, karl kleinpaste <notifications@github.com>
wrote:

> i figured i'd go ahead and do the CSS thing anyhow. what the heck...no
> matter what i do here, if the engine gets around to providing it some day,
> i'd have to change xiphos then anyhow, so why not do as much as i can for
> the time being.
>
> problem is, i've inserted a handler element in HTML_START (at the top of
> display.cc), and then replaced [i]...[/i] wrapping of the intro text with
> [div class="introMaterial"]...[/div] (interpolate angle brackets with me
> here). this has the unintended result that the entire chapter is
> italicized. *sigh* why does the bounding of [div]...[/div] not constrain
> the application of the .introMaterial spec?
>
> i've experimented with personalization of this in
> ~/.xiphos/default_style.css, to add "color: yellow" for .introMaterial, and
> yes indeed it turns the whole chapter yellow, not just the intro.
>
> example: at ESV2011 1Th.1.1, the block resulting from this change is:
>
> [div class="introMaterial"] [div sID="gen34165" type="introduction"/][br
> /] Paul wrote this letter to encourage new believers in their faith, to
> exhort them to godly living, to give them assurance about the eternal state
> of believers who had died, and to defend the integrity of his ministry as
> an apostle. Thessalonica (present-day Thessaloniki, Greece) was the capital
> of Roman Macedonia. It was on important trade routes. Paul, twice
> identified as the author (1:1; 2:18), visited Thessalonica on his second
> missionary journey but was forced to flee because of Jewish opposition. He
> sent Timothy to work with the largely Gentile church there, and Timothy
> brought him good news of their faith (3:6). This is one of Paul’s first
> letters, probably written about a.d. 50–51. [br /][div eID="gen34165"
> type="introduction"/][br /][br /] [/div]
>
> simple diff that generates this from today's source:
> display.cc.txt
> <https://github.com/crosswire/xiphos/files/1887959/display.cc.txt>
>
> is webkit misinterpreting the bounds of the standalone [div ... /]
> elements? i can hardly believe that would be the cause.
>
Most likely, yes. I don't think that "div" is allowed to be a self-closing
tag in HTML. I think you are required to have [div...] [/div]. I'm just
going from memory here, though, so it's possible I'm wrong. But, in
general, I believe the self-closing div is a no-no in the HTML world.

--Greg

**Comment by karlkleinpaste** [comment] 2018-04-09 12:04
yup, that's it.

i just crawled through gdb long enough to take a sample intro section and pseudo-manually obliterate all self-closing div to spaces. now the intro is italic and yellow.

ok -- for the time being, then, plain ol' [i]...[/i] is the operating solution, until some future unknowable day when a fix can be made to prevent sword from delivering self-closing div.

no, emphatically, i will not write code that examines intro text and obliterates bad div. i've already committed more than enough other sins in html content post-delivery hackery.

**Comment by karlkleinpaste** [comment] 2018-04-09 17:26
ok i lied. i couldn't help myself. i've committed one more html post-delivery hack.

alerque, for the upcoming release, and until a fix for sword happens, you can set a handler for .introMaterial in ~/.xiphos/default_style.css. mine looks like this...

body { -webkit-column-count: 2 ; margin-top: 0.1cm ; } .introMaterial { color:yellow }

...because i also like 2-column display most of the time, and i turn it off in individual modules when i don't want it, with style.css in such a module.

**Closed** 2018-04-09 17:26 UTC

**Comment by alerque** [comment] 2018-06-08 09:43
Thanks!
