### ISSUE TITLE
ver 4.2.0 Not opening study pad and editor  

### ISSUE THREAD

**Issue by geezuslvr** [crosswire/xiphos#1066] opened 2020-12-24 18:31 UTC
Kernel: 5.4.0-58-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Xfce 4.14.2 
           tk: Gtk 3.24.13 wm: xfwm4 dm: LightDM Distro: Linux Mint 20.1 Ulyssa 
           base: Ubuntu 20.04 focal

Xiphos 4.2.0 fails to open editor and study pad
Xiphos 4.1.0 Fails to save session, editor notes,study pad notes,and preferences.

(xiphos:8022): GLib-GObject-WARNING **: 10:13:27.232: invalid cast from 'GtkBox' to 'GtkButtonBox'

(xiphos:8022): Gtk-CRITICAL **: 10:13:27.232: gtk_button_box_set_layout: assertion 'GTK_IS_BUTTON_BOX (widget)' failed

**Comment by geezuslvr** [comment] 2020-12-24 18:36
(xiphos:8022): GLib-GObject-WARNING **: 10:13:27.232: invalid cast from 'GtkBox' to 'GtkButtonBox'

(xiphos:8022): Gtk-CRITICAL **: 10:13:27.232: gtk_button_box_set_layout: assertion 'GTK_IS_BUTTON_BOX (widget)' failed

**Comment by karlkleinpaste** [comment] 2020-12-24 18:38
can one of the PPA-related guys comment? @alerque?

**Comment by LAfricain** [comment] 2020-12-24 19:05
Study pad is nto working on the last xiphos release for debian. Do you install xiphos with the Ubuntu ppa?

**Comment by bgermann** [comment] 2021-01-11 16:36
This is a duplicate of #794

**Comment by LAfricain** [comment] 2022-01-31 09:30
I think this issue can be closed.

**Closed** 2022-01-31 11:31 UTC
