### ISSUE TITLE
two issues

### ISSUE THREAD

**Issue by mark4th** [crosswire/xiphos#814] opened 2017-08-02 23:09 UTC
forgot to change title to "Multiple issues" originally only had 2

Issue 1:
I cannot read dark text on a blinding wall of white background so I have selected a dark background with a slightly lighter foreground which gives a nice contrast between them and is not blindingly light.  When I switch to parallel view one of the texts displays in inverted colors and is utterly unreadable.
  
Please consider allowing me to select specific colors for both versions displayed under parallel view and not have one in the default colors and the other in inverted colors, this just does not work right with my custom colors.

Issue 2:

Clicking on a verse does not select it.  You have to click on the verse number.   Clicking on the verse number screws with the view position forcing me to readjust my visual focus point to somewhere OTHER than where I clicked in the first place.  IF I can click on it to select it there is no reason for you to adjust where the top of the view is and thus move the paragraph that was clicked on to somewhere else on the display.

Issue 3:

hitting cursor up/down does not advance/retreat the selected verse.

Issue 4:

While i can switch the display of the book I wish to read from the unreadable blinding wall of white which hurts my eyes after a few minutes, NOTHING ELSE can be switched out of blinding wall of white.  The modules tree to the left is always in blinding wall of white.  

Issue 5:

double clicking on a word highlights that word with a color that is not to be found anywhere in the preferences settings and renders said word unreadable with my preferences. 

Issue 6:

Double clicking on a word does not bring the dictionary definition of said word into the dictionary view.   

Issue 7

There are no tooltips for any of the funky little buttons scattered around the display.

**Comment by karlkleinpaste** [comment] 2017-08-09 12:13
a lot more than two issues...

- an update has been made to change parallel displays to use simple fg/bg alternation. 4.0.6 will be released by the weekend with the change.
- clicking on the verse# is deliberate, as clicking in text is intended either to request a word in the dictionary or to select text.
- arrow keys are used by the window widget to scroll the window itself. see the manual's "interface" section (Help->Contents, or F1, or http://xiphos.org/manual/interface#xiphos-shortcut) for keyboard shortcuts, specifically the n/p (next/previous) set.
- module tree, preview window, and certain other widgets are standard gtk elements whose color is (to my knowledge) not configurable at all. preferences' color configurability is applicable to all areas in which text is drawn.
- the double-click highlight color is a standard gtk thing, much as (in the windows world) selected text is typically highlighted blue. in my current build (gtk3 + webkit2), the highlight is grey, and i agree, it's not optimal, but it's a fixed thing that works well in high-contrast displays like straight b/w, but not so well when colors are altered.
- there is some inconsistency in double-click of a word. sometimes it simply highlights, other times it does the dictionary reference as intended. this seems highly dependent on how recent the webkit package is, against which xiphos is built.  i will look into it, but for myself at the moment, i see that dictionary reference works as expected though sometimes it takes double-clicking a 2nd time.
- i suppose i have to ask which buttons in which display. for the main window, there are precious few that are not explicitly labelled, notably the history mechanism beside the location bar, and even there the drop-down element between arrows has a tip. mod.mgr and preferences are chock full of tooltips. e.g. in mod.mgr install/update, hover on header icons; in adv.search, many buttons and even textual selectors have tips; in preferences->options, nearly every entry has tips. where do you find them missing?

**Comment by mark4th** [comment] 2017-08-09 14:45
lol yes i need to "L2 Count" or at least not click post till after I update the title, my bad :)

So sometimes I am getting tooltips for the widgets, other times it does not matter how long I hover I never get them.  I think this is because Im using a virtualbox Linux VM running inside a windows host and the computer does not always like the load i put on it :)

I do need to find a way to modify the blinding wall of white in the tree view, does that area have to be a "standard" widget?   It is not really consistent with themes, you get to change this bit over here but not that bit over there :/

ty for the update to the application and this bug report :)

**Comment by karlkleinpaste** [comment] 2017-08-09 22:53
gtk3 has gone mildly insane in making tooltip display delay longer than was the case in gtk2. i don't care to offer an explanation, if i had one. in any event, if you see a mouse-driven device that genuinely lacks a tooltip, and which is inexplicable without one, let me know and i'll add one, but those that don't have them (e.g. preferences "splash" toggle) are considered really, really obvious.

the sidebar upper widget for module tree etc is not something in which we draw, in the usual case as when scribbling text into the main panes like the bible and commentary. same for other structured widgets used that way, containing trees of some sort (modules, bookmarks) or other selectors (search doodads). sorry. if you happen to look around and find a way to change those colors, i should be able to incorporate them directly. in any event, the amount of "blinding wall of white" taken up by that widget is a pretty small fraction of the overall window.

the only thing remaining here to be addressed is whether double-click is actually working, and i can't determine that it's not, just that gtk3 is sensitive about whether one does so quickly enough (?) so as to induce word dictionary word selection. consequently i'm closing this now since the only actual code change that resulted was parallel fg/bg alternation.

**Closed by karlkleinpaste** 2017-08-09 22:53 UTC
