### ISSUE TITLE
drop-down menu for books partly off screen

### ISSUE THREAD

**Issue by vasyugan** [crosswire/xiphos#947] opened 2019-05-12 02:42 UTC
As you can see in the screenshot, the books in the dropdown menu are visible only until Daniel and there seems to be no way of getting the rest of the long drop down into display. For now, the only way of getting to NT books is by manually typing their name into the "address bar" to the right of the dropdown.

![Bildschirmfoto zu 2019-05-12 04-37-04](https://user-images.githubusercontent.com/3313208/57577095-d2e62200-746f-11e9-89ca-abfc9556208f.png)

**Comment by Bohooslav** [comment] 2019-05-12 06:17
But you can scroll it by two fingers on touchpad or scrolling by roll in mouse. Also there are buttons in the top and in the bottom of the field.
![Screenshot from 2019-05-12 09-14-32](https://user-images.githubusercontent.com/35796539/57578503-734f3d00-7496-11e9-933d-8ff3ca3dd12c.png)

**Comment by vasyugan** [comment] 2019-05-12 06:41
Am 12.05.19 um 08:17 schrieb Bohooslav:
>
> But you can scroll it by two fingers on touchpad or scrolling by roll
> in mouse.
>
Neither do anything here (Debian Buster with MATE)

> Also there are buttons in the top and in the bottom of the field.
>
Actually, there are one up and one downward pointing arrow right to the
dropdown menu. This one seems to work. Thanks for the hint!

**Comment by DavidHaslam** [comment] 2020-03-17 21:05
The **book selector** vertical scrolling works fine in the **Windows** edition of **Xiphos**.

Likewise the chapter number selector for **Psalms** - or any other book with more than a screen-full to select from.

Likewise the verse number selector for **Psalm 119** - or any other chapter with more than a screen-full to select from.

**Comment by alerque** [comment] 2020-03-18 11:34
I can confirm this is also currently functioning correctly with the latest git HEAD version on Arch Linux.

**Comment by karlkleinpaste** [comment] 2020-04-16 00:08
as i mentioned in #995, the application is not in general responsible for size calculations on dropdowns of this sort, rather the toolkit is expected to handle it automatically, including top/bottom arrow buttons.

**Comment by karlkleinpaste** [comment] 2020-04-18 16:32
a little googling tells me that this really is a gtk error, as seen in some distributions. some reports of this are quite old, some are relatively new, though none are really recent. this suggests to me that bugs have been fixed recently in gtk.
closing this, because it really isn't xiphos' problem, it's the toolkit's, to compute max viewable size and pack scroll arrows at top and bottom as needed. presumably as newer, fixed versions percolate out, users will stop seeing this.

**Closed by karlkleinpaste** 2020-04-18 16:32 UTC
