### ISSUE TITLE
SIGSEV when using HTTP mirrors

### ISSUE THREAD

**Issue by g4jc** [crosswire/xiphos#798] opened 2017-05-22 02:09 UTC
To reproduce:
1) Add a dummy HTTP source via Module Manager --> Add/Remove --> Add --> Source Type: "HTTP"
2) Choose --> Select new source --> press "Refresh".
3)  Crash.

  Thread 1 "xiphos" received signal SIGSEGV, Segmentation fault.
  sword::SWBuf::set (newVal=0xb26890 "ftp", this=0x40) at ../include/swbuf.h:189
  189	../include/swbuf.h: No such file or directory.
  Program terminated with signal SIGSEGV, Segmentation fault.
  The program no longer exists.

HTTP sources previously worked. It seems to be a regression caused by upstream SWORD... 
In any case I don't think it should SIGSEV if the download fails.

**Comment by karlkleinpaste** [comment] 2017-05-22 02:17
i don't reproduce it. is there some particular content to the dummy http source? when i add an arbitrary http with bogus content, it just fails to refresh and shows empty content.

**Comment by g4jc** [comment] 2017-05-22 03:17
For my test I entered:

Caption: Crosswire2
Type: HTTP
Host: ftp.crosswire.org.sdf
Directory: /pub/sword/raw/.sdf

So far I've been able to reproduce it on two different computers running Arch Linux with xiphos-git from AUR.

**Comment by karlkleinpaste** [comment] 2017-08-21 12:48
i've just come back to this, after months of inactivity.

i created my dummy source exactly per your suggestion. still, i get no crash -- just a more-or-less instantanteous failure (because the hostname is unknown, surely).

i've tried this in both fedora and win7, same result both places. i'm now suspecting a problem with arch, not with xiphos.

**Comment by karlkleinpaste** [comment] 2017-08-29 19:27
i'm closing this as unreproducible at this time. if it re-appears, file a new report and please be able to document with stack trace how and where it dies.  i genuinely don't think the code is at fault.

**Closed by karlkleinpaste** 2017-08-29 19:27 UTC
Labels: bug
