### ISSUE TITLE
4.0.6 still will not build on Fedora 26

### ISSUE THREAD

**Issue by justanenduser** [crosswire/xiphos#817] opened 2017-08-12 22:14 UTC
Fedora has moved on from webkitgtk3 to webkitgtk4. Xiphos is looking for either the original webkitgtk or webkitgtk3. 

This is a plain vanilla clean, configure and a failed build on a stock 64 bit Fedora 26.

[gary@bigboote xiphos-master]$ ./waf clean
'clean' finished successfully (0.036s)

[gary@bigboote xiphos-master]$ ./waf configure --prefix=/usr/local
Linux detected 
Check for program g++ or c++             : /usr/lib64/ccache/g++ 
Check for program cpp                    : /usr/bin/cpp 
Check for program ar                     : /usr/bin/ar 
Check for program ranlib                 : /usr/bin/ranlib 
Check for program gcc or cc              : /usr/lib64/ccache/gcc 
Check for program msgfmt                 : /usr/bin/msgfmt 
Check for program intltool-merge         : /usr/bin/intltool-merge 
Checking for header locale.h             : ok 
Check for program glib-genmarshal        : /usr/bin/glib-genmarshal 
Check for program glib-mkenums           : /usr/bin/glib-mkenums 
Check for program dbus-binding-tool      : /usr/bin/dbus-binding-tool 
Check for program docbook2man            : not found 
Check for program xml2po                 : /usr/bin/xml2po 
Check for program xsltproc               : /usr/bin/xsltproc 
Auto detecting gtk 3                     : ok 
Check for program strip                  : /usr/bin/strip 
Checking for dbus-glib-1 >= 0.60         : ok 
Checking for libgtkhtml4                 : ok 
Checking for GtkHTML Editor 4.0          : ok 
Checking for WebKit                      : fail 
Checking for pkg-config version >= 0.9.0 : ok 
Checking for GNOME related libs          : ok 
Checking for gtk+-unix-print-2.0         : ok 
Checking for sword                       : ok 
Checking for icu-i18n                    : ok 
Checking for biblesync                   : ok 
Checking for uuid                        : ok 
Checking for header dlfcn.h              : ok 
Checking for header inttypes.h           : ok 
Checking for header locale.h             : ok 
Checking for header memory.h             : ok 
Checking for header stdint.h             : ok 
Checking for header stdlib.h             : ok 
Checking for header strings.h            : ok 
Checking for header string.h             : ok 
Checking for header sys/stat.h           : ok 
Checking for header sys/types.h          : ok 
Checking for header unistd.h             : ok 
Checking for header sys/select.h         : ok 
Checking for header sys/socket.h         : ok 
Checking for header winsock.h            : not found 
Checking for function strcasestr         : ok 
'configure' finished successfully (2.089s)

[gary@bigboote xiphos-master]$ ./waf build
Waf: Entering directory `/home/gary/Downloads/xiphos-master/build'
[  1/133] glib_genmarshal: src/gnome2/marshal.list -> build/default/src/gnome2/marshal.h build/default/src/gnome2/marshal.c
[  2/133] glib_genmarshal: src/xiphos_html/marshal.list -> build/default/src/xiphos_html/marshal.h build/default/src/xiphos_html/marshal.c
[  3/133] glib_genmarshal: src/webkit/marshal.list -> build/default/src/webkit/marshal.h build/default/src/webkit/marshal.c
[  4/133] glib_genmarshal: src/examples/marshal.list -> build/default/src/examples/marshal.h build/default/src/examples/marshal.c
[  5/133] xml2po: help/fr/fr.po help/C/xiphos.xml -> build/default/help/fr/xiphos.xml
[  6/133] xml2po: help/fa/fa.po help/C/xiphos.xml -> build/default/help/fa/xiphos.xml
[  7/133] locale_set.c: src/gnome2/make-locale-set.sh po/LINGUAS -> build/default/src/gnome2/locale_set.c
[  8/133] copy: xiphos.desktop.in.in -> build/default/xiphos.desktop.in
[  9/133] dbus_binding_tool: src/gnome2/ipc-interface.xml -> build/default/src/gnome2/ipc-interface.h
[ 10/133] dbus_binding_tool: src/examples/ipc-interface.xml -> build/default/src/examples/ipc-interface.h
[ 11/133] po: po/ar.po -> build/default/po/ar.mo
[ 12/133] po: po/cs.po -> build/default/po/cs.mo
[ 13/133] po: po/cy.po -> build/default/po/cy.mo
[ 14/133] po: po/da.po -> build/default/po/da.mo
[ 15/133] po: po/de.po -> build/default/po/de.mo
[ 16/133] po: po/en_GB.po -> build/default/po/en_GB.mo
[ 17/133] po: po/es.po -> build/default/po/es.mo
[ 18/133] po: po/fa.po -> build/default/po/fa.mo
[ 19/133] po: po/fi.po -> build/default/po/fi.mo
[ 20/133] po: po/fr.po -> build/default/po/fr.mo
[ 21/133] po: po/he.po -> build/default/po/he.mo
[ 22/133] po: po/hu.po -> build/default/po/hu.mo
[ 23/133] po: po/it.po -> build/default/po/it.mo
[ 24/133] po: po/ja.po -> build/default/po/ja.mo
[ 25/133] po: po/ko_KR.po -> build/default/po/ko_KR.mo
[ 26/133] po: po/lt.po -> build/default/po/lt.mo
[ 27/133] po: po/lv.po -> build/default/po/lv.mo
[ 28/133] po: po/nb.po -> build/default/po/nb.mo
[ 29/133] po: po/nl.po -> build/default/po/nl.mo
[ 30/133] po: po/pl.po -> build/default/po/pl.mo
[ 31/133] po: po/pt.po -> build/default/po/pt.mo
[ 32/133] po: po/pt_BR.po -> build/default/po/pt_BR.mo
[ 33/133] po: po/ro.po -> build/default/po/ro.mo
[ 34/133] po: po/ru.po -> build/default/po/ru.mo
[ 35/133] po: po/sk.po -> build/default/po/sk.mo
[ 36/133] po: po/sl.po -> build/default/po/sl.mo
[ 37/133] po: po/sv.po -> build/default/po/sv.mo
[ 38/133] po: po/tr.po -> build/default/po/tr.mo
[ 39/133] po: po/zh_CN.po -> build/default/po/zh_CN.mo
[ 40/133] po: po/zh_TW.po -> build/default/po/zh_TW.mo
[ 41/133] xsltproc2po: help/xiphos.omf.in build/default/help/fr/xiphos.xml -> build/default/help/fr/xiphos-fr.omf
[ 42/133] xsltproc2po: help/xiphos.omf.in build/default/help/fa/xiphos.xml -> build/default/help/fa/xiphos-fa.omf
[ 43/133] xsltproc2po: help/xiphos.omf.in help/C/xiphos.xml -> build/default/help/C/xiphos-C.omf
[ 44/133] cxx: src/backend/gs_stringmgr.cpp -> build/default/src/backend/gs_stringmgr_1.o
[ 45/133] cxx: src/backend/module_manager.cc -> build/default/src/backend/module_manager_1.o
[ 46/133] cxx: src/backend/sword_main.cc -> build/default/src/backend/sword_main_1.o
[ 47/133] cxx: src/main/biblesync_glue.cc -> build/default/src/main/biblesync_glue_1.o
[ 48/133] cxx: src/main/configs.cc -> build/default/src/main/configs_1.o
[ 49/133] cxx: src/main/display.cc -> build/default/src/main/display_1.o
[ 50/133] cxx: src/main/export_passage.cc -> build/default/src/main/export_passage_1.o
[ 51/133] cxx: src/main/global_ops.cc -> build/default/src/main/global_ops_1.o
[ 52/133] cxx: src/main/lists.cc -> build/default/src/main/lists_1.o
[ 53/133] cxx: src/main/mod_mgr.cc -> build/default/src/main/mod_mgr_1.o
[ 54/133] cxx: src/main/module_dialogs.cc -> build/default/src/main/module_dialogs_1.o
[ 55/133] cxx: src/main/modulecache.cc -> build/default/src/main/modulecache_1.o
In file included from ../src/xiphos_html/xiphos_html.h:29:0,
                 from ../src/main/display.cc:44:
../src/webkit/wk-html.h:30:10: fatal error: webkit/webkit.h: No such file or directory
 #include <webkit/webkit.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Waf: Leaving directory `/home/gary/Downloads/xiphos-master/build'
Build failed:  -> task failed (err #1): 
	{task: cxx display.cc -> display_1.o}

This is a clean and a failed configure on a stock 64 bit Fedora 26 specifying webkit2.

[gary@bigboote xiphos-master]$ ./waf configure --prefix=/usr/local --enable-webkit-editor --enable-webkit2
Linux detected 
Check for program g++ or c++             : /usr/lib64/ccache/g++ 
Check for program cpp                    : /usr/bin/cpp 
Check for program ar                     : /usr/bin/ar 
Check for program ranlib                 : /usr/bin/ranlib 
Check for program gcc or cc              : /usr/lib64/ccache/gcc 
Check for program msgfmt                 : /usr/bin/msgfmt 
Check for program intltool-merge         : /usr/bin/intltool-merge 
Checking for header locale.h             : ok 
Check for program glib-genmarshal        : /usr/bin/glib-genmarshal 
Check for program glib-mkenums           : /usr/bin/glib-mkenums 
Check for program dbus-binding-tool      : /usr/bin/dbus-binding-tool 
Check for program docbook2man            : not found 
Check for program xml2po                 : /usr/bin/xml2po 
Check for program xsltproc               : /usr/bin/xsltproc 
Auto detecting gtk 3                     : ok 
Check for program strip                  : /usr/bin/strip 
Checking for dbus-glib-1 >= 0.60         : ok 
Checking for pkg-config version >= 0.9.0 : ok 
Checking for GNOME related libs          : not found 
/home/gary/Downloads/xiphos-master/wscript:369: error: the configuration failed (see '/home/gary/Downloads/xiphos-master/build/config.log')

This the config.log file... notice that the last check for GNOME related libs is looking for webkitgtk3 which is no longer a part of Fedora, they have moved on to webkitgtk4.

# project xiphos (4.0.6) configured on Sat Aug 12 14:50:31 2017 by
# waf 1.5.15 (abi 7, python 2070df0 on linux2)
# using ./waf configure --prefix=/usr/local --enable-webkit-editor --enable-webkit2
#

----------------------------------------
Check for program g++ or c++
  find program=['g++', 'c++'] paths=[] var='CXX'
  -> '/usr/lib64/ccache/g++'

----------------------------------------
Check for program cpp
  find program=['cpp'] paths=[] var='CPP'
  -> '/usr/bin/cpp'

----------------------------------------
Check for program ar
  find program=['ar'] paths=[] var='AR'
  -> '/usr/bin/ar'

----------------------------------------
Check for program ranlib
  find program=['ranlib'] paths=[] var='RANLIB'
  -> '/usr/bin/ranlib'

----------------------------------------
Check for program gcc or cc
  find program=['gcc', 'cc'] paths=[] var='CC'
  -> '/usr/lib64/ccache/gcc'

----------------------------------------
Check for program msgfmt
  find program=['msgfmt'] paths=[] var=None
  -> '/usr/bin/msgfmt'

----------------------------------------
Check for program intltool-merge
  find program=['intltool-merge'] paths=[] var='INTLTOOL'
  -> '/usr/bin/intltool-merge'

----------------------------------------
Checking for header locale.h
==>
#include <locale.h>

int main() {
	return 0;
}

<==
[1/2] [32mcxx: build/.conf_check_0/test.cpp -> build/.conf_check_0/testbuild/default/test_1.o
[0m['/usr/lib64/ccache/g++', '-Idefault', '-I../../../../../../../usr/include', '../test.cpp', '-c', '-o', 'default/test_1.o']
[2/2] [33mcxx_link: build/.conf_check_0/testbuild/default/test_1.o -> build/.conf_check_0/testbuild/default/testprog
[0m['/usr/lib64/ccache/g++', 'default/test_1.o', '-o', '/home/gary/Downloads/xiphos-master/build/.conf_check_0/testbuild/default/testprog']
ok

----------------------------------------
Check for program glib-genmarshal
  find program=['glib-genmarshal'] paths=[] var='GLIB_GENMARSHAL'
  -> '/usr/bin/glib-genmarshal'

----------------------------------------
Check for program glib-mkenums
  find program=['glib-mkenums'] paths=[] var='GLIB_MKENUMS'
  -> '/usr/bin/glib-mkenums'

----------------------------------------
Check for program dbus-binding-tool
  find program=['dbus-binding-tool'] paths=[] var='DBUS_BINDING_TOOL'
  -> '/usr/bin/dbus-binding-tool'

----------------------------------------
Check for program docbook2man
  find program=['docbook2man'] paths=[] var='SGML2MAN'
  -> ''

----------------------------------------
Check for program xml2po
  find program=['xml2po'] paths=[] var='XML2PO'
  -> '/usr/bin/xml2po'

----------------------------------------
Check for program xsltproc
  find program=['xsltproc'] paths=[] var='XSLTPROC2PO'
  -> '/usr/bin/xsltproc'

----------------------------------------
Auto detecting gtk 3
pkg-config --errors-to-stdout --print-errors --modversion gtk+-3.0
3.22.17
ok

----------------------------------------
Check for program strip
  find program=['strip'] paths=[] var=None
  -> '/usr/bin/strip'

----------------------------------------
Checking for dbus-glib-1 >= 0.60
pkg-config --errors-to-stdout --print-errors --atleast-version=0.60 dbus-glib-1
pkg-config --errors-to-stdout --print-errors --cflags --libs dbus-glib-1
-I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0 
ok

----------------------------------------
Checking for pkg-config version >= 0.9.0
pkg-config --errors-to-stdout --print-errors --atleast-pkgconfig-version=0.9.0
ok

----------------------------------------
Checking for GNOME related libs
pkg-config --errors-to-stdout --print-errors "gconf-2.0" "gmodule-2.0" "glib-2.0" "libgsf-1 >= 1.14" "libxml-2.0" --cflags --libs "gtk+-3.0"  "webkitgtk-3.0"  
Package webkitgtk-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `webkitgtk-3.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'webkitgtk-3.0', required by 'virtual:world', not found
not found

**Comment by greg-hellings** [comment] 2017-08-12 22:19
--enable-webkit-editor and --enable-webkit2 are mutually exclusive. wscript should be updated to reflect that, but for now, --enable-webkit-editor will automatically override and cause waf to ignore the --enable-webkit2 option.

WebKit Editor is only going to work with webkit1 APIs. Porting the editor the WebKit2 is not yet completed. There is a build of 4.0.6 for Fedora 26 that I just completed (I maintain the packaging for it). You can find it in Bodhi https://bodhi.fedoraproject.org/updates/FEDORA-2017-af4945324c. It will make its way into updates-testing on the next compose, but you can test the build results immediately by downloading the RPMs from the builds tab at that page.

I would appreciate it if you test the build and provide feedback in Bodhi/Bugzilla if there are issues.

**Comment by greg-hellings** [comment] 2017-08-12 22:20
This is a duplicate of #794, in disguise.

**Closed by greg-hellings** 2017-08-12 22:19 UTC

**Comment by justanenduser** [comment] 2017-08-12 22:27
Thank you. Sigh... again I make a mistake. The build I just did using the
4.0.6 xiphos source from GitHub is giving me every appearance and behaviour
of working. God Bless and many thanks.

-gary-

**Comment by greg-hellings** [comment] 2017-08-12 22:29
Oh, you didn't make a mistake. We should make it clearer that these two are mutually exclusive and should probably even issue a warning when they are both enabled. That's on us, the maintainers, to get that part right! That's why I have #794  open to track updating our scripts to properly capture that deficiency.
