### ISSUE TITLE
Module Manager problems in 4.0.7 (Ubuntu Linux)

### ISSUE THREAD

**Issue by MEAdams** [crosswire/xiphos#831] opened 2017-10-18 15:09 UTC
Did a compete removal of previous Xiphos version (4.0.4 from Ubuntu) and installed 4.0.7 from the Crosswire ppa, Started Xiphos from a terminal in Ubuntu 16.04, select Edit->Module Manager, select Module Sources->Add/Remove, select Load Standard button. Application locks for about 30 seconds, then opens a Xiphos message window stating, "Could not load standard sources from CrossWire." Close message window, close Module Manager, application locks up. Messages in the terminal I had opened Xiphos in states, "Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged." and "(xiphos:29952): Gtk-CRITICAL **: gtk_list_store_clear: assertion 'GTK_IS_LIST_STORE (list_store)' failed". Xiphos locks when I try to close it with a message, "This window is not responding, Do you want to force the application to exit, or wait for it to respond?" Xiphos must be forced to quit. Even without trying to do anything in the Module Manager (i.e. simply opening it and closing it), the Xiphos application will lock up and must be forced to quit as described.

Additional observation: Upon opening Xiphos, the Book, Chapter and Version spinner controls each display double up/down arrows. Moving the mouse cursor over the spinners reduces them down to single spinners. Might not be related, but could be a GUI pointer lost somewhere.

**Comment by LAfricain** [comment] 2017-11-17 14:39
> Additional observation: Upon opening Xiphos, the Book, Chapter and Version spinner controls each display double up/down arrows. Moving the mouse cursor over the spinners reduces them down to single spinners. Might not be related, but could be a GUI pointer lost somewhere.

Same issue with the xiphos from ppa.

**Comment by DavidHaslam** [comment] 2017-11-25 16:10
The doubled up/down spinners happens on Windows too. See #829

**Comment by karlkleinpaste** [comment] 2018-04-08 23:26
the doubled arrows have been fixed (#829, #877).
experimenting with Load Standard, i use it now and again and have never seen it cause grief. that's the case right now. do you know if crosswire.org was responding otherwise when you tried previously? could you try again and see if the problem persists?
xiphos will indeed get "stuck" while its attention is (by design and intention) momentarily closely concerned with finding the standard repo list. but it's just busy, not hung or spinning. if crosswire.org is off the net at the time, i could see how this could cause an apparent (if unreal) hang but it's a tough thing to test when crosswire.org is happily responding, as now.

**Comment by karlkleinpaste** [comment] 2018-04-15 20:54
closing this for now, lacking specific information about what could go wrong here. if a concrete repeat-by can be offered in the future, this can be re-opened and analyzed.

**Closed by karlkleinpaste** 2018-04-15 20:54 UTC
