### ISSUE TITLE
fails to run in Debian testing due to incorrect version of libsword

### ISSUE THREAD

**Issue by martin-id** [crosswire/xiphos#917] opened 2018-11-15 06:49 UTC
when run in a terminal, the error is : ian@x250:~$ /usr/bin/xiphos
/usr/bin/xiphos: error while loading shared libraries: libsword-1.7.4.so: cannot open shared object file: No such file or directory

on my system( uname -a returns: Linux x250 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-11-02) x86_64 GNU/Linux ), libsword-1.8.1-3 is the current and installed version.

**Comment by ildar** [comment] 2018-11-15 12:58
I suggest this kind of bugs is good for Debian bugzilla. What do you think?

**Comment by greg-hellings** [comment] 2018-11-15 14:08
@martin-id There's lots of questions here, but this definitely isn't a bug with Xiphos.

How did you install Xiphos? How did you install Sword? If you installed them both from apt, then you will need to file a bug with Debian to have the Xiphos package rebuilt against the newer Sword package. If you installed them from source, you will need to rebuild Xiphos against the newer version of Sword.

**Comment by refdoc** [comment] 2018-11-16 08:50
Compilation from source allows combination of a wide variety of versions. This does not mean that independently compiled versions can be arbitrarily recombined. That aside, the source of libsword is C++, the source of xiphos is C. Not java.Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [crosswire/xiphos] fails to run in Debian testing due to incorrect version of libsword (#917)From: martin-id To: crosswire/xiphos CC: Subscribed Xiphos was installed via apt, and I've never installed libsword independently.
For C++ in a configure.ac file the library is defined by requiring a least version x.y.z (e.g. libsword-1.7 >= 1.7.0 ) to allow for bugfixing the library; I've seen this bug before where the compile control file uses == instead of >=, which limits the programme's flexibility unnecessarily.  I'm not a Debian guru, but if the library does need to be locked down to a specific version I think the debian control file should specifically mandate the version required; as that file is part of each package so I don't believe you can blame Debian.
I'd go looking in the source, but I'm not familiar with Java so I'm pretty sure I'd mess it up :(

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@martin-id in #917: Xiphos was installed via apt, and I've never installed libsword independently.\r\n\r\nFor C++ in a configure.ac file the library is defined by requiring a least version x.y.z (e.g. libsword-1.7 \u003e= 1.7.0 ) to allow for bugfixing the library; I've seen this bug before where the compile control file uses == instead of \u003e=, which limits the programme's flexibility unnecessarily.  I'm not a Debian guru, but if the library does need to be locked down to a specific version I think the debian control file should specifically mandate the version required; as that file is part of each package so I don't believe you can blame Debian.\r\n\r\nI'd go looking in the source, but I'm not familiar with Java so I'm pretty sure I'd mess it up :(\r\n"}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/917#issuecomment-439316850"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/crosswire/xiphos/issues/917#issuecomment-439316850",
"url": "https://github.com/crosswire/xiphos/issues/917#issuecomment-439316850",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [crosswire/xiphos] fails to run in Debian testing due to incorrect version of libsword (#917)",
"sections": [
{
"text": "",
"activityTitle": "**martin-id**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@martin-id",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"crosswire/xiphos\",\n\"issueId\": 917,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"crosswire/xiphos\",\n\"issueId\": 917\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/crosswire/xiphos/issues/917#issuecomment-439316850"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 410828852\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by refdoc** [comment] 2018-11-16 12:33
To expand on my previous email,If you did install via apt-get and did not compile either part (libsword, xiphos) then the fault lies with Debian. Alert them and check from time to time if they fixed it. If you compiled either from source then you need compile the other one too. Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [crosswire/xiphos] fails to run in Debian testing due to incorrect version of libsword (#917)From: martin-id To: crosswire/xiphos CC: Subscribed Xiphos was installed via apt, and I've never installed libsword independently.
For C++ in a configure.ac file the library is defined by requiring a least version x.y.z (e.g. libsword-1.7 >= 1.7.0 ) to allow for bugfixing the library; I've seen this bug before where the compile control file uses == instead of >=, which limits the programme's flexibility unnecessarily.  I'm not a Debian guru, but if the library does need to be locked down to a specific version I think the debian control file should specifically mandate the version required; as that file is part of each package so I don't believe you can blame Debian.
I'd go looking in the source, but I'm not familiar with Java so I'm pretty sure I'd mess it up :(

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@martin-id in #917: Xiphos was installed via apt, and I've never installed libsword independently.\r\n\r\nFor C++ in a configure.ac file the library is defined by requiring a least version x.y.z (e.g. libsword-1.7 \u003e= 1.7.0 ) to allow for bugfixing the library; I've seen this bug before where the compile control file uses == instead of \u003e=, which limits the programme's flexibility unnecessarily.  I'm not a Debian guru, but if the library does need to be locked down to a specific version I think the debian control file should specifically mandate the version required; as that file is part of each package so I don't believe you can blame Debian.\r\n\r\nI'd go looking in the source, but I'm not familiar with Java so I'm pretty sure I'd mess it up :(\r\n"}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/917#issuecomment-439316850"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/crosswire/xiphos/issues/917#issuecomment-439316850",
"url": "https://github.com/crosswire/xiphos/issues/917#issuecomment-439316850",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [crosswire/xiphos] fails to run in Debian testing due to incorrect version of libsword (#917)",
"sections": [
{
"text": "",
"activityTitle": "**martin-id**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@martin-id",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"crosswire/xiphos\",\n\"issueId\": 917,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"crosswire/xiphos\",\n\"issueId\": 917\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/crosswire/xiphos/issues/917#issuecomment-439316850"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 410828852\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by teusbenschop** [comment] 2018-11-17 15:49
This bug has now been fixed, it was fixed yesterday. 
When running Xiphos now, in Debian Testing, it loads the correct libraries.
The cause of the bug was an incorrect library transition, done by me - oops!
But it was fixed now in a correct library transition.

**Closed** 2020-04-18 20:16 UTC
