### ISSUE TITLE
Windows: Splash screen stuck, program unresponsive

### ISSUE THREAD

**Issue by thegreyshadow** [crosswire/xiphos#865] opened 2018-02-24 19:35 UTC
I use Xiphos without problem in my main OS (Slackware64-current) but now I have to teach a course on Biblical Hebrew and I have something to recommend to my Windows-using students, so I thought about Xiphos.

However, I ran into a showstopper problem.

I run Windows 10 Fall Creator's Update, 64 bit.

Upon installing both Xiphos installers for Windows (version 4.0.7, both 32 and 64-bit), the program installs OK. Upon first run the program prompts me to install modules, etc. But when it's the time to run the actual program, the splash screen is stuck at the last stage (IIRC it is "showing Xiphos"). And the main program window is unresponsive.

I installed the versions SpaRV, SpaSEV, WLC and OBHS.
Thanks and blessings,

Eduardo

**Comment by karlkleinpaste** [comment] 2018-04-08 04:40
this is an irregularly recurring report that we've seen since our windows port was first completed, almost a decade ago.
in fact, xiphos is not permanently hung. it is stuck...for a while...but it will come loose and finish startup. we have looked repeatedly for the cause of this and have never come up with an answer. significantly, this occurs exactly once, the very first time xiphos is first installed on a new system. thereafter, startup is its usual reasonably zippy self.
i regret having to close this, but we've addressed this several times in the past, to no resolution. i would love to find what windows thinks it's doing, but as you may imagine, the testing aspect borders on impossibility: any system where it occurs sees it exactly once, and thereafter never again. i have no clue how to go about examining the problem in a general sense.

**Closed by karlkleinpaste** 2018-04-08 04:40 UTC
