### ISSUE TITLE
Module Manager problems in Xiphos 4.0.7 (win32) during attempts to install Update module

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#826] opened 2017-09-27 12:28 UTC
Just tried installing a module from the **eBible.org** repository.
Repository refresh worked fine.

**Xiphos 4.0.7** (Win32) just closed (crashed?) during attempt to install module.
No progress bar movements prior to the crash. The behaviour is repeatable.

Installing one from **CrossWire Main** worked OK.

Is there something wrong at eBible.org ?
Probably not, as I can install a module from there into **PocketSword**.

So has Karl inadvertently done something in Xiphos that makes installing from eBible.org crash? 

**Clarification - further evidence.**

I was able to install a _new_ module from eBible.org

Xiphos closed **ONLY** when I selected a module under **Updates** and attempted to install that.
[Or if I note the name of such a module, look for it under Bibles, and attempt to install it from there.]

After the crash, the Xiphos MM _no longer listed the same module_ under Updates even after a further refresh.
Moreover, there was _no corresponding new conf file_ in the **mods.d** folder.

Seems to be a bug in how Module Manager handles Updates.

I will soon run out of _displayed_ **Updates** if I continue testing.
There were 7 before I began, and now there are only 3.

It would help if someone else could also test and reproduce the same bug under Windows.

**Comment by DavidHaslam** [comment] 2017-09-27 12:29
The problem has also been reported in the sword-devel mailing list in the thread that announced the Xiphos 4.0.7 release.

**Comment by DavidHaslam** [comment] 2017-09-27 18:08
**Further evidence:**
Attempting to installed an _updated_ module from the **IBT** repository gave exactly the same symptoms.

**Comment by DavidHaslam** [comment] 2017-09-29 16:03
**Further evidence:**
Attempting to installed an updated module from the **IBT** repository gave exactly the same symptoms.

**Comment by DavidHaslam** [comment] 2017-09-29 16:06
OK - I just re-installed **Xiphos 4.0.6a** to see if the updates no longer visible would reappear.

They didn't !

Those that failed to install via Xiphos 4.0.7 are no longer listed as updates.

The prompts the serious question, _Where is the false information being held?_

**Comment by DavidHaslam** [comment] 2017-09-29 16:12
Installing updated module via **Xiphos 4.0.6a** still works OK.

**Comment by jmichae3** [comment] 2017-10-12 02:22
ftp for syberduck, fz client, and any other ftp seems to be broken on windows, and I think this includes xiphos' ftp. I could install no modules. not even one FTP client works. maybe this is a microsoft bug.

wsastartupa and wsock32.dll is a problem.

**Comment by DavidHaslam** [comment] 2017-10-12 20:08
@jmichae3 &ndash; that may be an unrelated problem. 
Better to add a _new_ issue than merely comment here.

**Comment by DavidHaslam** [comment] 2017-11-25 16:11
Can anyone else reproduce this issue?  Or am I alone?

@karlkleinpaste

**Comment by karlkleinpaste** [comment] 2018-04-08 23:45
the underlying function of the mod.mgr has not changed in eons. there is assuredly no sensitivity to any particular repo in its design, other than loading standard repo list from crosswire.org.

it is in fact true that "update" is implemented as "delete, then install" because update in the underlying Sword lib InstallMgr class has never worked properly -- it has a tendency to run off into the weeds of trying to install many more files than are intended. i once took part in trying to fix this some years ago, but gave up without resolution and just left the delete/install habit continue. the effect and result is the same, of course.

the information regarding repos' available modules is held in (for windows) c:/users/NAME/Application Data/Sword/InstallMgr. the date-stamped directories can be correlated against masterRepoList.conf to determine which date-stamp represents which repo. under that area, one finds the mods.d content representing what the repo offers.

due to this report, i have been experimenting occasionally for literally months, to see if i could run into a situation where this would fail; i have yet to see it happen. if it's still happening, i need some kind of data on circumstances. as matters stand, i have access to 1 win7 and 2 win10 machines, plus wine under linux, for testing purposes and cannot get any of them to cough up a problem anything like this. i admit to some suspicion about the machine configuration (viz. windows bugs) leading to death of xiphos for no good reason.

unreproducible and hard-to-reproduce errors are a difficult matter to address. i will surely try to fix any problem found in the mod.mgr, but at this point i simply cannot find a circumstance where it fails in my own environments.

**Comment by DavidHaslam** [comment] 2018-04-09 13:25
Understood. It's a mystery!

I'll try again when 4.0.8 release is available. 

4.0.6 is still OK for me at present.

**Comment by karlkleinpaste** [comment] 2018-04-15 20:52
absent current repeat-by, i'm closing this for now. it can be re-opened if some distinct new information comes along.

**Closed by karlkleinpaste** 2018-04-15 20:52 UTC
