### ISSUE TITLE
Misleading proximity of Strong's tags to the next line

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#990] opened 2020-03-18 11:41 UTC
When (e.g.) **Strong's numbers** are enabled in module settings, the numbers are closer to the next line than to the line they actually belong to.

This is misleading to some extent.

Enabling **Double spacing** does not improve the matter.
That only has any effect when there are no tags enabled.

**Comment by LAfricain** [comment] 2020-03-18 14:21
Wow!!! 3 hours ago I wanted to open this issue!! But I had something urgent to do... And you did :)
A picture can help:

![strong_spacement](https://user-images.githubusercontent.com/19690477/76970359-0fa26580-692c-11ea-9ccc-7f97ae374b2b.png)

**Comment by karlkleinpaste** [comment] 2020-04-16 00:40
heavy *sigh*
this is an annoying artifact of webkit's varying-over-releases habits. i agree it's misleading to some extent, but the problem is that, as of just a couple xiphos releases ago, it was actually perfectly fine in placement, where the numbers (and lemmas) were well-positioned relative to base text.

i will see if i can improve on this with some adjustment to the stack specification, but it's not pretty, it's not reliable because of changing webkit habit, and it'll look wrong again in another year or two after webkit undergoes its own updates.

**Comment by karlkleinpaste** [comment] 2020-04-18 15:14
i've now looked at this a bit, and without changing anything, the spacing looks to have become much more correct. this would indicate that (no surprise to me) webkit updates have occurred. here's several screenshots of 1Tim.3 in various Grk and Grk interlinear modes, with Strong's, lemmatization, and morphology. i think the spacing looks pretty good. unless someone gives me a good reason, i'm going to close this as some flavor of "unreproducible" or "fixed by other work" or whatever the relevant github-supported tag is.

![screenshot1](https://user-images.githubusercontent.com/7548920/79641478-ca10cc80-8165-11ea-8bb2-36f2b4564ab8.png)
![screenshot2](https://user-images.githubusercontent.com/7548920/79641484-cc732680-8165-11ea-87f2-518e9b24ef01.png)
![screenshot3](https://user-images.githubusercontent.com/7548920/79641485-ced58080-8165-11ea-9195-ddcedf3e3d35.png)

**Comment by LAfricain** [comment] 2020-04-18 18:12
Hi,
Did you test with a bible only with strong numbers? With version of webkit are you speaking about?

**Comment by karlkleinpaste** [comment] 2020-04-18 21:28
hm, well, the problem seems to be that I tested only with greek bibles, and perhaps my chosen greek font works better with the spacing.

looking now at NASB and KJV w/Strong's... yeah, it's still a problem.

pity. the greek modules look rather good.

**Closed** 2020-04-18 21:59 UTC

**Comment by LAfricain** [comment] 2020-04-19 07:34
Thank you Karl for this solution.
