### ISSUE TITLE
Xiphos 4.07 problem on Ubuntu

### ISSUE THREAD

**Issue by byroniac** [crosswire/xiphos#884] opened 2018-04-15 21:17 UTC
[dotsword.zip](https://github.com/crosswire/xiphos/files/1913400/dotsword.zip)
[dotxiphos.zip](https://github.com/crosswire/xiphos/files/1913402/dotxiphos.zip)

I'm not an Ubuntu developer. However, I cannot install or update any modules from eBible.org using Xiphos 4.07 on Ubuntu 18.04 Bionic. I had the same issue with 4.07 when I built it from source on Ubuntu 17.10, but not with the 4.04 version from the 17.10 repositories. Currently, I'm using 4.07 from the 18.04 repositories. When I'm in the module manager, every module works fine, except if I choose eBible.org, then the Install/Updates window goes blank. So I have to install/update manually. I've tried running Xiphos from the Ubuntu CLI to see what it would say, but all it says is, "GtkDialog mapped without a transient parent. This is discouraged." I think all the other module repo sources work fine, just not the eBible.org one. So I don't know if this is a bug, or not, but I remember it working in 4.04 on Ubuntu 17.10 using the Ubuntu-specific build in their repositories. For reference, on 18.04, I have installed xiphos, xiphos-data, sword-comm-mhcc, sword-comm-scofield, sword-comm-tdavid, sword-dict-naves, sword-dict-strongs-greek, sword-dict-strongs-hebrew, sword-text-kjv, sword-text-web.

EDIT: I don't have this problem with Windows 10 Xiphos, 32-bit or 64-bit. I'm on 64-bit Ubuntu, but can't test the 32-bit version, because only xiphos:i386 is available, and for some reason xiphos-data:i386 is not. The 64-bit versions are installed instead.

**Comment by karlkleinpaste** [comment] 2018-04-15 21:40
i've had recurring complaints about ebible.org, but never with enough detail to reproduce what's wrong.

i just tried it myself with my current from-github-source build, on fedora 27. it works fine for me using either the standard ebible configuration (via ftp) or its alternate configuration (using http). you can find which one you're using by looking in ~/.sword/InstallMgr/InstallMgr.conf.

is it possible that a firewall rule is in your way? it would seems unlikely but your description varies between 17.10 and 18.04 and i'm not sure if there's a consistent presentation there. there is surely no difference in how the mod.mgr operates from one repo to the next, esp. when they are all configured by default as ftp repos. if you happen to try to retrieve a repo's module list while the host is not available on the network, then you would surely get an empty set and the Install/Update pane would be blank. that is the only explanation i can offer at this time. if you have more detail about configuration, network condition, repo host availability, or other matters, let me know.

**Comment by byroniac** [comment] 2018-04-15 21:51
No firewalls here, except my cable modem. Well, so far, I can get to (in my web browser) ftp://ftp.ebible.org/sword and http://ebible.org/sword just fine (my configuration had the FTP one, so I added HTTP, but still no cigar). It's very weird. I think it may be a problem with the site itself? But it works on Windows 10, so I don't know. I'm going to take a stab at trying to build it from Git on 18.04, though I'm not really a Linux developer. I'll post back the results.

[General]
PassiveFTP=true

[Sources]
FTPSource=Bible.org|ftp.bible.org|/sword|||20090514005700
FTPSource=CrossWire|ftp.crosswire.org|/pub/sword/raw|||20081216195754
FTPSource=CrossWire Attic|ftp.crosswire.org|/pub/sword/atticraw|||20120224005100
FTPSource=CrossWire Beta|ftp.crosswire.org|/pub/sword/betaraw|||20090224125400
FTPSource=CrossWire Wycliffe|ftp.crosswire.org|/pub/sword/wyclifferaw|||20120711005000
FTPSource=Deutsche Bibelgesellschaft|ftp.crosswire.org|/pub/sword/dbgraw|||20171021160700
FTPSource=IBT|ftp.ibt.org.ru|/pub/modsword/raw|||20120224005200
FTPSource=Xiphos|ftp.xiphos.org|.|||20090514005900
FTPSource=eBible.org|ftp.ebible.org|/sword|||20151110161300
HTTPSource=eBible.org (HTTP)|eBible.org|/sword|||20180415164700

**Comment by byroniac** [comment] 2018-04-15 22:04
Well, can't build either the 4.07 or Git versions, because i don't have libgtkhtml4-(anything) available in my 18.04 repository. Rats. Thanks for your help.

**Comment by refdoc** [comment] 2018-04-15 22:29
On Sun, 2018-04-15 at 15:04 -0700, Byron Smith wrote:
> Well, can't build either the 4.07 or Git versions, because i don't
> have libgtkhtml4-(anything) available in my 18.04 repository. Rats.
> Thanks for your help.

./waf configure --with-webkit-editor-enabled or some such

**Comment by byroniac** [comment] 2018-04-15 23:09
@refdoc I followed the website instructions but I don't have libgtkhtml4 for some reason (or any version of libgtkhtml, for that matter, but hopefully once 18.04 is officially released, I will, as i seem to remember it being available on 17.10):

Check out the current GIT source tree with:

git clone https://github.com/crosswire/xiphos.git

Then build under Linux using:

cd xiphos
./waf configure --prefix=/usr --gtk=3 --enable-webkit2
./waf build
sudo ./waf install

**Comment by refdoc** [comment] 2018-04-16 06:11
These instructions are incomplete insofar as Debian and its derivates are concerned. GTKHTML is deprecated and won't come back. You will need to add the option I referenced to your configure line. Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [crosswire/xiphos] Xiphos 4.07 problem on Ubuntu (#884)From: Byron Smith To: crosswire/xiphos CC: Peter von Kaehne ,Mention @refdoc I followed the website instructions but I don't have libgtkhtml4 for some reason (or any version of libgtkhtml, for that matter, but hopefully once 18.04 is officially released, I will, as i seem to remember it being available on 17.10):
Check out the current GIT source tree with:
git clone https://github.com/crosswire/xiphos.git
Then build under Linux using:
cd xiphos
./waf configure --prefix=/usr --gtk=3 --enable-webkit2
./waf build
sudo ./waf install

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@byroniac in #884: @refdoc I followed the website instructions but I don't have libgtkhtml4 for some reason (or any version of libgtkhtml, for that matter, but hopefully once 18.04 is officially released, I will, as i seem to remember it being available on 17.10):\r\n\r\nCheck out the current GIT source tree with:\r\n\r\ngit clone https://github.com/crosswire/xiphos.git\r\n\r\nThen build under Linux using:\r\n\r\ncd xiphos\r\n./waf configure --prefix=/usr --gtk=3 --enable-webkit2\r\n./waf build\r\nsudo ./waf install\r\n"}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/884#issuecomment-381445610"}}}

**Comment by byroniac** [comment] 2018-04-16 07:58
The --enable-webkit-editor switch for waf was the missing key; thanks. I was able to build it, and now it works. Except, I chose the /usr/local prefix and specifically have to call it using /usr/local/bin/xiphos instead of /usr/bin/xiphos even though /usr/local/bin has precedence on my $PATH. I am not sure what's up with that. I built it with sword 1.8.1, so maybe that's the solution? Thanks.

**Comment by karlkleinpaste** [comment] 2018-04-16 22:36
i have no explanation for $PATH precedence problems, but as long as you can build your own and get sensible mod.mgr access to eBible, i'm closing this.
rebuild with "waf configure --prefix=/usr" if you wish merely to overwrite what was previously there.

**Closed by karlkleinpaste** 2018-04-16 22:36 UTC

**Comment by byroniac** [comment] 2018-04-16 23:06
@karlkleinpaste I did completely uninstall my distribution version of Xiphos (after my comment), so now I don't really need the /usr/local prefix and I may uninstall, rebuild, and install directly to /usr maybe. Thanks!
@refdoc  Thanks so much for the programming help!
